version: '3.1'

services:

  bus-data-collector: 
    build:
      context: .
    networks:
      - default
    depends_on: 
      - db
    environment:
      BUS_ROUTES: "52,6"
      # keep 6 running from 19/05 to 26/05 to get an entire continuous week's worth

  bus-data-collector-2: 
    build:
      context: .
    networks:
      - default
    depends_on: 
      - db
    environment:
      BUS_ROUTES: "452,9"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    expose:
      - '5432'
    networks:
      - default
    volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresBusData:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


# `docker-compose build`
# `docker-compose up`