version: '3.1'

volumes:
  db:

services:

  bus-data-collector: 
    build:
      context: .
    environment: 
      DATABASE_URL: postgres://todoapp@postgres/todos
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresBusData:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


# `docker-compose build`
# `docker-compose up`