version: '3.1'

services:

  # bus-data-collector: 
  #   build:
  #     context: .

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


# `docker-compose build`
# `docker-compose up`